name: look around

on: 
  push: 

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: open seasame
        run: |
          #sudo apt update  
          sudo apt install tor
          sudo npm install -g @treehouses/cli
          sudo treehouses tor add 22
          sudo treehouses tor
          sudo treehouses tor notice now
          sudo treehouses sshkey github adduser dogi
          sudo treehouses sshkey github adduser rjpadilla
          sudo treehouses sshkey github adduser jlkwong
          sudo treehouses sshkey github adduser dyeh123
          sudo npm i -g capture-website-cli --unsafe-perm=true
          capture-website https://dev.planetfarms.io/login --output=/screenshots/login.png
          capture-website https://dev.planetfarms.io/register --output=/screenshots/register.png
          sync
          # echo "shh only dreams"
          # sleep 1200
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: /screenshots

